### ISSUE TITLE
how to run rasa actions on heroku

### ISSUE THREAD

**Issue by ankithans** [just-ai/rasa-heroku-template#4]

**Comment by ankithans** [comment]
I figured out we have to deploy two servers one for `rasa run` and the other for `rasa run actions`.
Is there any other way?

**Comment by morfeusys** [comment]
@ankithans it maybe more appropriate to include actions into the Docker you'd like to deploy rather than deploy two different servers

**Comment by ankithans** [comment]
yup you are right . I have used docker-compose to do so.
